Parsers refactor(Code, VLIWCode and contet), deparse(and download) functionality and small fixes
etsiiull/SIMDE pull request #69
Opened 2023-11-04 16:51 UTC by endes0

This PR refactors all the 3 parsers present in the code, replacing the old Lex dependency with ts-parsec. While it maintains retrocompatibility with the old file formats, this new parsers are more flexible(EX: The first line, with indicate the number of instructions is not necessary anymore).
This Pr also implements a new functionality, deparsing, allowing to download content and code from the interface. 
Finally, it fixes some bugs. A notorious example is that test in subdirs were currently not being executed with` npm run test`

2023-11-05 17:55 UTC, oxcabe commented on src/core/Common/Code.ts
Looks way better now!

2023-11-05 18:20 UTC, oxcabe requested changes
Good implementation. There is still a lot of room for improvement, though! Try to avoid writing all these `// TODO: ...` comments. Next time, instead, do a follow-up issue that references the working PR with the future implementations or refactor you find necessary.

It'd also be best practice to run a code formatter tool (such as [Prettier](https://prettier.io/)) that tidies the files you are about to commit. I wouldn't bother doing it for this PR, but could be something mandatory if we decide to integrate something like [Husky](https://github.com/typicode/husky) after the Vite tooling refactor issue https://github.com/etsiiull/SIMDE/issues/66 is fulfilled.

I'd also recommend you to use a [LSP-based](https://github.com/typescript-language-server/typescript-language-server) linter for TypeScript if you aren't already using one. This is something that will probably be configured in the future directly into the TypeScript building process, or through the Husky integration.

Submit the requested changes and we're good to go. Thank you for your contribution!

2023-11-05 18:20 UTC, oxcabe commented on src/core/Common/InstructionFormats.ts
> +    NooP                            // NOP
Refactor this to `Noop`

2023-11-05 18:20 UTC, oxcabe commented on src/i18n/locales/en/common.json
> +            "download_memory": "Download Memory(JSON)",
Use camelCase for any JSON fields you create or modify

2023-11-05 18:20 UTC, oxcabe commented on src/core/Common/Code.ts
> +        // WHaat why we are reinventing the wheel using a linked list?
Avoid writing comments like this one 😅

2023-11-05 18:22 UTC, oxcabe commented
Oh, and one last thing. Rename the PR title to adhere to the [Conventional Commits v1.0.0 standard](https://www.conventionalcommits.org/en/v1.0.0/).

2023-11-06 15:50 UTC, endes0 commented
> Good implementation. There is still a lot of room for improvement, though! Try to avoid writing all these `// TODO: ...` comments. Next time, instead, do a follow-up issue that references the working PR with the future implementations or refactor you find necessary.


I have to admit that at the end I rushed this PR and I forgot to do the usual cleanup commit, fixing it now.

> 
> It'd also be best practice to run a code formatter tool (such as [Prettier](https://prettier.io/)) that tidies the files you are about to commit. I wouldn't bother doing it for this PR, but could be something mandatory if we decide to integrate something like [Husky](https://github.com/typicode/husky) after the Vite tooling refactor issue #66 is fulfilled.
> 
> I'd also recommend you to use a [LSP-based](https://github.com/typescript-language-server/typescript-language-server) linter for TypeScript if you aren't already using one. This is something that will probably be configured in the future directly into the TypeScript building process, or through the Husky integration.
> 
> Submit the requested changes and we're good to go. Thank you for your contribution!

Yes, I am using VSCode with I think have an LSP-based linter and a code formatter (which I also forgot to use) by default. Btw, I tought that the project had already a linter configured during build or at least there is an `lint` script and config(`tslint.json`) present.

2023-11-07 14:24 UTC, oxcabe approved these changes

2023-11-07 14:32 UTC, merged